#!/usr/bin/env bash

exit_on_error() {
    echo "Error occured!"
    exit 1
}

cd $OPENVPN_CA_DIR

sed -i "s/\(^export KEY_COUNTRY=\)\".*\"/\1\"US\"/" vars || exit_on_error
sed -i "s/\(^export KEY_PROVINCE=\)\".*\"/\1\"MyProvince\"/" vars || \
    exit_on_error
sed -i "s/\(^export KEY_CITY=\)\".*\"/\1\"MyCity\"/" vars || exit_on_error
sed -i "s/\(^export KEY_ORG=\)\".*\"/\1\"MyOrganization\"/" vars || \
    exit_on_error
sed -i "s/\(^export KEY_EMAIL=\)\".*\"/\1\"my@mail.com\"/" vars || \
    exit_on_error
sed -i "s/\(^export KEY_OU=\)\".*\"/\1\"MyUnit\"/" vars || exit_on_error
sed -i "s/\(^export KEY_NAME=\)\".*\"/\1\"MyServer\"/" vars || exit_on_error

ln -s openssl-1.0.0.cnf openssl.cnf || exit_on_error

source vars

./clean-all || exit_on_error
./build-ca --batch || exit_on_error
./build-key-server --batch MyServer || exit_on_error
./build-dh || exit_on_error
